export const GET_CONTACTS = "GET_CONTACTS";
export const CURRENT_PAGE = "CURRENT_PAGE";
export const INCREASE_CURRENT_PAGE = "INCREASE_CURRENT_PAGE";
export const GET_MORE_CONTACTS = "GET_MORE_CONTACTS";